### ISSUE TITLE
My game ends without a reason

### ISSUE THREAD

**Issue by gregoriofrancisco99** [EmanuelcPereira/Jogo_da_cobrinha_DIO#1]
I played your snack game, and I found it interesting. You had a great job pulling that off.
But for some reason, my game ends with no reason. It'd be awesome if you fix it.

I have one more idea, what if you put a "restart, pause, quit game" option. It'd be more realistic, you know!

Give me a sign if you need a hand. Good coding!

**Comment by EmanuelcPereira** [comment]
Hi Gregorio,

This snack game I did following a free course video to learn Javascript. Follow below the link to the video series. In the course videos have explanations about the game behavior. Maybe will be more interesting for you to watch the videos.

https://web.digitalinnovation.one/project/recriando-o-jogo-da-cobrinha-com-javascript/learning/a41588bb-45b0-41ce-a7d3-20012199fb11?back=/track/html-web-developer&bootcamp_id=9fb3f492-ea99-4055-82cb-c364f18706ec

**Comment by gregoriofrancisco99** [comment]
Okay, I understand. But have you ever planed to improve it?

**Comment by EmanuelcPereira** [comment]
Not yet

**Comment by gregoriofrancisco99** [comment]
Uhn, I see. I'll try to follow the tutorial course, to see it by myself. Thanks for the link
